// fazer um gatilho de inserir uma pessoa em duas tabelas 
CREATE TRIGGER BKP_INS_PESSOA 
AFTER INSERT ON PESSOA
FOR EACH ROW

BEGIN
INSERT INTO BACKUP_PESSOA (IDPESSOA, NOME, SEXO, EMAIL, OPERACAO) VALUES (NEW.IDPESSOA, NEW.NOME, NEW.SEXO, NEW.EMAIL, 'insert');


END$
// CHAMAR PROCEDURE
CALL CADPESSOA('ANGELA', 'F', 'ANGE@GMAIL.COM')$
Call CADPESSOA('SIMONE','F','SIMONE@gmail.com')$
DELETE FROM PESSOA WHERE IDPESSOA = '1'$